### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by XXAnass02XX** [XXAnass02XX/Delaunay-Triangulation-With-CUDA#1]
- [ ] Shared Memory for Bad Triangle Detection
- [ ] The addEdgeIfUnique function could be parallelized using a reduction pattern to find duplicate edges
- [ ] Use Grid-Stride Loops for Large Triangle Sets
- [ ] The removeTriangle operation could be parallelized at the block level
- [ ] Ensure triangle data is stored in a structure-of-arrays format rather than array-of-structures to enable coalesced memory access
